"""reading sessions by user and time

Revision ID: 0002
Revises: 0001

The Stats page loads one reader's sessions since a date; this index serves it.
Create Date: 2026-10-02 15:53:16.870761

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reading_sessions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_reading_sessions_user_created", ["user_id", "created_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reading_sessions", schema=None) as batch_op:
        batch_op.drop_index("ix_reading_sessions_user_created")

    # ### end Alembic commands ###
